project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "1 - A Layered Grammar of Graphics: ggplot2 methods"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "2 - Beyond ggplot2 Fundamentals"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
        - text: "3.1 - Programming Interactive Data Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex031.html"
        - text: "3.2 - Programming Animated Statistical Graphics with R"
          href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex032.html"
        - text: "4.1 - Visualising Distribution"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex041.html"
        - text: "4.2 - Visual Statistical Analysis"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex042.html"
        - text: "4.3 - Visualising Uncertainty"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex043.html"
        - text: "4.4 - Funnel Plots for Fair Comparisons"
          href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex044.html"
        - text: "5.1 - Building Ternary Plot with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex051.html"
        - text: "5.2 - Visual Correlation Analysis"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex052.html"
        - text: "5.3 - Visual Multivariate Analysis with Heatmap"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex053.html"
        - text: "5.4 - Visual Multivariate Analysis with Parallel Coordinates Plot."
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex054.html"
        - text: "5.5 - Treemap Visualisation with R"
          href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex055.html"
      - text: "In-class Exercise"
        menu: 
        - text: "4 - Fundamentals of Visual Analytics"
          href: In-class_Ex/In-class_Ex04/In-class_Ex04.html
        - text: "5"
          href: In-class_Ex/In-class_Ex05/In-class_Ex05.html
        - text: "6"
          href: In-class_Ex/In-class_Ex06/In-class_Ex06.html
        - text: "7"
          href: In-class_Ex/In-class_Ex07/In-class_Ex07.html
        - text: "8"
          href: In-class_Ex/In-class_Ex08/In-class_Ex08.html
        - text: "9"
          href: In-class_Ex/In-class_Ex09/In-class_Ex09.html
        - text: "10"
          href: In-class_Ex/In-class_Ex10/In-class_Ex10.html
      - text: "Take-home Exercise"
        menu: 
        - text: "1 - Creating data visualisation beyond default"
          href: Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html
    right:
      - href: index.qmd
        text: Home
      - text: "{{< iconify fa6-brands linkedin size=2xl >}}"
        href: 'https://www.linkedin.com/in/nguyenbaothuphuong/'
format:
  html:
    theme: zephyr
    css: styles.css
    toc: true
    number-sections: true
    code-copy: true

editor: visual

